#!/usr/bin/env python3
"""Render the human-readable standards catalog from the YAML source of truth."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / "data" / "standards-catalog.yaml"
DEFAULT_OUTPUT = ROOT / "references" / "standards-catalog.md"

ROLE_LABELS = {
    "governing-framework": "Governing frameworks",
    "document-system": "Document and information systems",
    "content-language-profile": "Content and language profiles",
    "controlled-language": "Controlled languages",
    "normative-keyword-system": "Normative keyword systems",
    "terminology-method": "Terminology methods",
    "interchange-format": "Interchange formats",
    "process-standard": "Process standards",
    "accessibility-requirement": "Accessibility requirements",
    "informative-guidance": "Informative accessibility guidance",
    "editorial-guide": "Editorial guides",
}

ROLE_ORDER = list(ROLE_LABELS)


def load_catalog(path: Path) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("catalog root must be a mapping")
    return data


def bullets(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items)


def render_profile(profile: dict[str, Any]) -> str:
    designation = profile["designation"]
    lines = [
        f"### {designation} — {profile['name']}",
        "",
        f"- **Registry ID:** `{profile['id']}`",
        f"- **Authority:** {profile['authority']}",
        f"- **Role:** `{profile['role']}`",
        f"- **Status:** `{profile['status']}`",
        f"- **Publication:** {profile.get('publication_date') or 'living guidance'}",
        f"- **Access:** `{profile['access']}`",
        f"- **Official source:** {profile['official_source']}",
        f"- **Last verified:** {profile['last_verified']}",
        "",
        f"**Lifecycle:** {profile['lifecycle_note']}",
        "",
        "**Use for**",
        "",
        bullets(profile["scope"]),
        "",
        "**Do not use as**",
        "",
        bullets(profile["exclusions"]),
        "",
        "**Conformance prerequisites**",
        "",
        bullets(profile["conformance_prerequisites"]),
        "",
    ]
    return "\n".join(lines)


def render(data: dict[str, Any]) -> str:
    profiles = data["profiles"]
    grouped: dict[str, list[dict[str, Any]]] = {role: [] for role in ROLE_ORDER}
    for profile in profiles:
        grouped.setdefault(profile["role"], []).append(profile)

    lines = [
        "# Standards Catalog",
        "",
        "> Generated from `./data/standards-catalog.yaml`. Do not edit this file directly.",
        "",
        f"- **Registry schema:** {data['schema_version']}",
        f"- **Registry reviewed:** {data['last_reviewed']}",
        f"- **Freshness warning:** {data['freshness_warning_days']} days",
        "",
        "Use this catalog as a routing aid, not as authoritative standard text. Edition, lifecycle, role, access, scope, exclusions, and conformance prerequisites are explicit so unlike sources do not compete as peer writing styles.",
        "",
        "## Role model",
        "",
        "| Role | Function |",
        "|---|---|",
        "| governing-framework | Binding or precedence-setting drafting and safety framework |",
        "| document-system | Information-product structure, lifecycle, and quality |",
        "| content-language-profile | Audience-facing wording and structure |",
        "| controlled-language | Constrained vocabulary and grammar |",
        "| normative-keyword-system | Obligation, recommendation, permission, and capability |",
        "| terminology-method | Concepts, definitions, preferred terms, and relations |",
        "| interchange-format | Machine exchange rather than prose style |",
        "| process-standard | Professional workflow rather than sentence style |",
        "| accessibility-requirement | Accessibility outcomes and conformance requirements |",
        "| informative-guidance | Supplemental guidance without automatic normative force |",
        "| editorial-guide | Practical publication and word-level conventions |",
        "",
        "## Selection patterns",
        "",
        "| Task | Typical route |",
        "|---|---|",
        "| ordinary message or routine copyedit | no external profile required |",
        "| general public explanation | ISO 24495-1; add a jurisdictional guide only when useful |",
        "| Canadian accessible communication | CAN-ASC-3.1 plus applicable federal or organization guidance |",
        "| API tutorial | ISO/IEC/IEEE 26514 plus Google developer style; WCAG when web delivery is in scope |",
        "| software requirements | ISO/IEC/IEEE 29148 plus RFC 2119/8174 or applicable ISO/IEC drafting rules |",
        "| maintenance procedure | IEC/IEEE 82079-1 plus ASD-STE100 when controlled language adds value; governing safety framework when hazards exist |",
        "| terminology governance | ISO 704 plus approved glossary; TBX only for machine exchange |",
        "| legal explanation | ISO 24495-2 plus governing jurisdiction and legal review |",
        "| public science communication | ISO 24495-3 plus scientific subject-matter review |",
        "| full human MT post-editing | ISO 18587 plus terminology and source-content profiles |",
        "",
    ]

    for role in ROLE_ORDER:
        items = sorted(grouped.get(role, []), key=lambda p: p["designation"].lower())
        if not items:
            continue
        lines.extend([f"## {ROLE_LABELS[role]}", ""])
        for profile in items:
            lines.append(render_profile(profile))

    unknown_roles = sorted(set(grouped) - set(ROLE_ORDER))
    for role in unknown_roles:
        lines.extend([f"## Other: {role}", ""])
        for profile in sorted(grouped[role], key=lambda p: p["designation"].lower()):
            lines.append(render_profile(profile))

    lines.extend([
        "## Conflict precedence",
        "",
        "1. Law and regulation.",
        "2. Contract, procurement requirement, certification scheme, or governing publication rules.",
        "3. Approved organization terminology, policy, schema, and product contracts.",
        "4. Domain or document system.",
        "5. Safety and preservation of factual or normative meaning.",
        "6. Accessibility and localization requirements.",
        "7. General plain-language principles.",
        "8. Editorial preferences.",
        "",
        "Report unresolved conflicts instead of silently blending incompatible rules.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rendered = render(load_catalog(args.source))
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"generated catalog is stale: run {Path(__file__).name}")
        print("Generated standards catalog is current.")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"Wrote {args.output.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
